version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  simulator:
    environment:
      - BROKERS=rabbitmq
      - PORT
      - USER
      - PASSWORD
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.sim
  listener:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.lst
    volumes:
      - ./messaging/output_files:/usr/src/app/messaging/output_files
    environment:
      - BROKERS
      - PORT
      - USER
      - PASSWORD
